os:
- linux
services:
- docker
language: node_js
node_js:
- 10.13.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.gradle"
env:
  global:
  - NODE_VERSION=10.13.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: ENAwX2EmA8Wx4nSICcA2hJIKPG5UAk6Z7jz1LLTfbo75VW/Ywh12mCvpVG9mX2p05aX0yln8S4w/8afg9G0NcPMlMf/5eifOcXmrDNgW92hPwLhaKyQnkWXZB7J4MxLigpyTGm2AyDMPEVrAzvbJLHnOOdDchTsgYaJiFAL8IW5blfj1Kc8rmc2dMCW2ujMtzBQsWgjWLrDVneK9pM014sYheiWVskkwly6pR33/98qefO1SkJyQyA5lG4xA7zqZ2GCj9MzxmOBu45bMSe3gOYFLFrS38YsaXv1/BTWHT6ZacYuBOIWYg0AXqlfy0Mbc+zI/HMhPbUr491YXIFgVOxLCMeo5l6NwAxz2WS1YOJQ9+sINPaj6PpmOFut6BoNavx2npMcEdP6sjXQWRukCtsQoYD8vRXjDUU/0zxRwoZmCAySz344uV0oeaI6ol/9s7anqJNAgtPj+3kqmN/AiyDFqFhs57uPuL9n10a96UeUzhTwcC86/gK9lpZbhjq4/NdPF5Z8Nt2f/hZwqvuZWCaVfNYyqstGPrf3aiC0m8veQwvCCqk0G5hfWgE79UnNuQLNf58NRiQeE2R2BoE8fYynTrOxKWcSrgImY59W+jkXtWqSQGrhTLeV4bgokJHSQp5RsfbrXKwhCy2Ow5IgxfNYrzj/uiLR0BtZ2jLHTKm8=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
install:
- npm install
script:
- chmod +x gradlew
- "./gradlew clean test"
- npm test -- -u
- "./gradlew sonarqube --no-daemon -Dsonar.organization=sebogado-github -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONAR_TOKEN"
- "./gradlew bootWar -Pprod -x test"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
