os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.13.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=10.13.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
addons:
    sonarcloud:
        organization: sebogado-github
        token:
            secure: rbsdEW7kaM5b3Y2EcmgmcKZTwz8o6KlYdxlfYGrbMgB7BiO0JzRgH2OFctzW2Fx4DVNctlTNpOYT//K1YaQYe22qFqcamf25QZypuG7r1sRLbU6Q4wgLjyjt2dnJ0LqXxpfFJ3uR5Br/agvwfuEEHTZySKYwDx+xN2gL525aMHSzwiongLeKX57VVm5Ce82k0/GCbV0bteog4W0uQ2jqx2Z0Qf862E4bv3tZcDnFctOWIA99Q6zG+AAYuln7N/a0mbHsbtB17tS1eByn1u932UWHZQtzb8rEyMDrNNILggwCBdimhZlKbrCsNQ73F88li8ah4SfJnnQvKjRgOeMYUxoj5aeEfkPha21t5EmFBWMXgpMKSjsYlz9ngkOptrNPtIrG17xM6H6SKzDTNnqWTS+HaMgIj+MlYz0YNU5sNk2vK2ZVsRVh8UFBYWFfgGr8WGLShePHrzKsX0EyDCD09IhDXCD6hX9Ogjat2L13P3aX8kHVFo9Ma2jziDM6AQx3xJynZmiOR98mF4fz0CXH5J5eYZzWeecMaHLclRBEkow/4V0hkGyrRvjWbPTWeifWaUFDX3TYHE0vpSmNse4VN8vWlgSXrwgMEWvH857tsL11sGIYdzJaLjSwK4jAJVtNeMUJPgf1/fn3Ztt2QGha0gjK6r+dOmw7Ynq2u5ymS/Q=
script:
  - chmod +x gradlew
  - ./gradlew clean test
  - npm test -- -u
  - ./gradlew bootWar -Pprod -x test
  - sonar-scanner
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
